version: "24.0.7"
services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql-wall-street
    restart: always                       # always restart
    environment:
      MYSQL_DATABASE: 'test'              # name of database
      MYSQL_USER: 'dico'                # sample is the name of user
      MYSQL_PASSWORD: 'root'          # password for sample user
      MYSQL_ROOT_PASSWORD: 'root'     # password for root user
    ports:
      - '3307:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
        mysql-db: